language: node_js
matrix:
  include:
    - node_js: "4.4"
    - node_js: "5"
    - node_js: "6"
    - node_js: "7"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
install:
  - npm install
script:
  - npm run test
  