language: node_js
matrix:
  include:
    - node_js: "6"
    - node_js: "7"
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/lighthouse/lighthouse-core/scripts/download-chrome.sh
script:
  - yarn run grunt-example
